const shows = [
  {
    name: 'National Dahlia Show',
    startDate: '20220922',
    endDate: '20220925',
    org: 'American Dahlia Society, National Capitol Dahlia Society',
    link: 'https://2022-national-dahlia-show.org',
    location: 'Sheraton Reston Hotel, Reston, VA',
    file: null,
  },
  {
    name: 'CDS Dahlia Show',
    startDate: '20220827',
    endDate: null,
    org: 'Connecticut Dahlia Society',
    link: 'http://www.ctdahlia.org',
    location: 'Elizabeth Park, 1561 Asylum Ave, West Hartford, CT 06117, USA',
    file: null,
  },
  {
    name: 'RIDS Dahlia Show',
    startDate: '20220910',
    endDate: '20220911',
    org: 'Rhode Island Dahlia Society',
    link: 'https://rhodeislanddahliasociety.org',
    location:
      'North Kingston Community Center (formerly Coldspring Community Center), Beech Street, Wickford, RI',
    file: null,
  },
  {
    name: 'LIDS Dahlia Show',
    startDate: '20220903',
    endDate: '20220904',
    org: 'Long Island Dahlia Society',
    link: 'https://www.longislanddahlia.org/',
    location:
      'The Bayard Cutting Arboretum, 440 Montauk HWY Great River, NY 11739',
    file: null,
  },
  {
    name: 'Rochester Dahlia Society',
    startDate: '20220917',
    endDate: null,
    org: 'Rochester Dahlia Society',
    link: 'https://www.rochesterdahlias.org',
    location: 'Bristol’s Garden Center, 7454 Route 96, Victor, NY 14564',
    file: null,
  },
  {
    name: 'GDS Dahlia Show',
    startDate: '20221001',
    endDate: '20221002',
    org: 'Greenwich Dahlia Society',
    link: 'https://greenwichbotanicalcenter.org/gds/',
    location: 'Greenwich Botanical Center, 130 Bible St, Cos Cob, CT 06807',
    file: null,
  },
  {
    name: 'NEDS Dahlia Show',
    startDate: '20220917',
    endDate: '20220918',
    org: 'New England Dahlia Society',
    link: 'http://newenglanddahliasociety.org',
    location: 'Tower Hill Botanic Garden, 11 French Dr, Boylston MA 01505',
    file: null,
  },
  {
    name: 'Washington County Fair',
    startDate: '20220820',
    endDate: null,
    org: 'Rhode Island Dahlia Society',
    link: null,
    location: 'Agricultural Building, 78 Richmond Townhouse Road, Richmond, RI',
    file: null,
  },
  {
    name: 'Woodstock Fair',
    startDate: '20220902',
    endDate: '20220905',
    org: null,
    link: 'https://www.woodstockfair.com/',
    location: '281 Route 169 South Woodstock, CT 06267',
    file: null,
  },
  {
    name: 'Mid Island Dahlia Show',
    startDate: '20220817',
    endDate: '20220818',
    org: 'Mid Island Dahlia Society',
    link: null,
    location:
      'Burns Horticultural Conference Center, 1395 Planting Fields Road, Oyster Bay, NY 11771',
    file: null,
  },
];

export default shows;
